program = block "." ;

block = [ "const" ident "=" number {"," ident "=" number} ";"]
        [ "var" ident {"," ident} ";"]
        { "procedure" ident ";" block ";" } statement ;

statement = [ ident ":=" expression | "call" ident 
              | "?" ident | "!" expression 
              | "begin" statement {";" statement } "end" 
              | "if" condition "then" statement 
              | "while" condition "do" statement ];

condition      = "odd" expression | equality;
equality       = expression ("=="|"!="|"<"|"<="|">"|">=") expression;
expression     = [ "+"|"-"] factor { ("+"|"-") factor};
factor         = primary {("*"|"/") primary};
primary        = ident | number | "(" expression ")";
